name: Deploy to EC2

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t kurento-app:latest .
          docker tag kurento-app ${{ secrets.DOCKER_USERNAME }}/kurento-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/kurento-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: 13.124.5.88
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull  ${{ secrets.DOCKER_USERNAME }}/kurento-app:latest
            docker stop kurento-container || true
            docker rm kurento-container || true
            docker run -d --name kurento-container -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/kurento-app:latest